@apiURL=http://localhost:8080
@token={{$dotenv TEMP_TOKEN}}

###
GET {{apiURL}}/notes
Authorization: Bearer {{token}}

###
POST {{apiURL}}/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "note": "Min nya note med JWT"
}

###
PUT {{apiURL}}/notes/66ebdb3b4e5bd611f3ab5ea4
Content-Type: application/json

{
    "note": "gå på krog"
}