@apiURL=http://localhost:8080

###
GET {{apiURL}}/notes

###
POST {{apiURL}}/notes
Content-Type: application/json

{
    "note": "Min nya note 3"
}

###
PUT {{apiURL}}/notes/66ebdb3b4e5bd611f3ab5ea4
Content-Type: application/json

{
    "note": "gå på krog"
}